name: Test Script

on:
  push:
    branches: [ testing ]

jobs:
  test:
    name: Test FLINT build script
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Collect Workflow Telemetry
        uses: thundra-io/workflow-telemetry-action@v1
        
      - name: Run Script
        run: |
          chmod +x AppImage_FLINT_Build.sh
          ./AppImage_FLINT_Build.sh
