name: Test Script

on:
  push:
    branches: [ testing ]

jobs:
  test-20:
    name: Test 20.04 FLINT build script
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Collect Workflow Telemetry
        uses: thundra-io/workflow-telemetry-action@v1
        
      - name: Run Script
        run: |
          chmod +x AppImage_FLINT_Build.sh
          ./AppImage_FLINT_Build.sh
          pwd
        
  test-22:
    name: Test FLINT 22.04 build script
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Collect Workflow Telemetry
        uses: thundra-io/workflow-telemetry-action@v1
        
      - name: Run Script
        run: |
          chmod +x AppImage_FLINT_Build.sh
          ./AppImage_FLINT_Build.sh
          curl bashupload.com -T FLINT-f6125df-x86_64.AppImage
          pwd
          
#       - name: Save artifacts
#         uses: actions/upload-artifact@v3
#         with:
#           name: AppImage-Ubuntu-22.04
#           path: /home/runner/Downloads/FLINT/Source/build
        
